package com.agritrace.edairy.desktop.finance.ui;

public interface FinanceBindingConstants {

	// from ViewConstants
	String ID_BTN_BATCH_ENTRY = "ID_BTN_BATCH_ENTRY";

	String FILTER_TXT_MEMBER_LOOKUP = "FILTER_TXT_MEMBER_LOOKUP";
	String FILTER_TXT_REF_NO = "FILTER_TXT_REF_NO";
	String FILTER_COMBO_STORE = "FILTER_COMBO_STORE";
	String FILTER_DATE_START_DATE = "FILTER_COMBO_START_DATE";
	String FILTER_DATE_END_DATE = "FILTER_COMBO_END_DATE";
	String FILTER_CHOICE_TX_SOURCE = "FILTER_CHOICE_TX_SOURCE";

	// member transaction edit panel
	String ID_TRANSACTION_CHOICE = "TRANSACTION_CHOICE";

	String ID_STORE_SALE_CHOICEBTN = "STORE_SALE_BTN";
	String ID_VETERINARY_CHOICEBTN = "VETERINARY_BTN";
	String ID_SHARE_DEDUCTION_CHOICEBTN = "SHARE_DEDUCTION_BTN";
	String ID_PAYMENT_CHOICEBTN = "PAYMENT_BTN";

	String ID_TRANSACTION_DATE = "TRANSACTION_DATE";
	String ID_DAIRY_LOCATION_COMBO = "DAIRY_LOCATION_COMBO";
	String ID_REF_NUMBER_TEXT = "REF_NUMBER_TEXT";
	String ID_TRANSACTION_AMOUNT_TEXT = "TRANSACTION_AMOUNT_TEXT";
	String ID_RECORD_ID_TEXT = "RECORD_ID_TEXT";
	String ID_MEMBER_NAME_TEXT = "MEMBER_NAME_TEXT";
	String ID_MEMBER_LOOKUP_BTN = "MEMBER_LOOKUP_BTN";
	String ID_TRANSACTION_DESCRIPTION_TEXT = "TRANSACTION_DESCRIPTION_TEXT";
	String ID_CHECK_NUMBER_TEXT = "CHECK_NUMBER_TEXT";
	String ID_SIGNED_BY_TEXT = "SIGNED_BY_TEXT";

	// from Form
	String BTN_SAVE_ALL_RECORDS = "btnSaveAllRecords";
	String BTN_CANCEL_ALL = "btnCancelAll";
	String BTN_VIEW = "btnView";
	String BTN_DELETE = "btnDelete";
	String DETAIL_TABLE_RIDGET = "detailTable";
	String BTN_ADD_TRANSACTION = "btnAddTransaction";
	String BTN_CLEAR_CURRENT = "btnClearCurrent";
	String LBL_MEMBER_NAME_RIDGET = "lblMemberName";
	String SIGNED_BY_TEXT_RIDGET = "signedByText";
	String CHK_NO_TEXT_RIDGET = "chkNoText";
	String AMT_TEXT_RIDGET = "amtText";
	String GRP_TRANSACTIONS_TBLLABEL = "grpTransactions";

	static final String RECORD_ID_TEXT = "recordIdText";
	static final String DESC_TEXT = "descText";

}
