<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dairy"
    nsURI="http://com.agritrace.edairy.desktop.common.model/dairy/" nsPrefix="dairy">
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrationNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="make" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engineNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chassisNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logBookNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insurancePolicyNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceExpirationDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dominantColour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacityInTonnes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assetInfo" eType="#//Asset"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="assetInfo"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Embedded"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleId" eType="ecore:EDataType common.ecore#//UniqueID">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="vehicleId"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Id"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionJournalLine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordedMember" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flagged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitOfMeasure" lowerBound="1"
        eType="ecore:EEnum common.ecore#//UnitOfMeasure" defaultValueLiteral="KILOGRAMS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notRecorded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validatedMember" eType="#//Membership"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offRoute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="ecore:EClass farm.ecore#//Farm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="farmContainer" lowerBound="1"
        eType="ecore:EClass farm.ecore#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dairyContainer" eType="ecore:EClass farm.ecore#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionJournal" eType="#//CollectionJournal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rejected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="common.ecore#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="id"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobFunction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nationalId" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nhifNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nssfNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DairyLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Id"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Id&#xA;@GeneratedValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOpened" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" eType="#//Route"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="ecore:EClass common.ecore#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functions" upperBound="-1"
        eType="#//DairyFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionJournal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="journalEntries" upperBound="-1"
        eType="#//CollectionJournalLine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="journalDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="session" lowerBound="1"
        eType="#//Session" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" lowerBound="1"
        eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" lowerBound="1" eType="#//Route"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="farmContainer" lowerBound="1"
        eType="ecore:EClass farm.ecore#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bin" lowerBound="1" eType="#//DairyContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1"
        eType="#//Vehicle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driverTotal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordTotal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        defaultValueLiteral="0" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="journalId" lowerBound="1"
        eType="ecore:EDataType common.ecore#//UniqueID">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="journalId"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Id"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Id"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Id&#xA;@GeneratedValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stops" upperBound="-1"
        eType="#//DairyLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trip">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collections" lowerBound="1"
        upperBound="-1" eType="#//CollectionJournal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliveries" lowerBound="1"
        upperBound="-1" eType="#//DeliveryJournal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="started" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ended" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tripId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" changeable="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="tripId"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Id&#xA;@GeneratedValue"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeliveryJournal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dairy" eSuperTypes="common.ecore#//Company">
    <eOperations name="getMemberFarms" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass farm.ecore#//Farm"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrationNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nhifNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nssfNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="federalPin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licenseEffectiveDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licenseExpirationDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberships" upperBound="-1"
        eType="#//Membership" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branchLocations" upperBound="-1"
        eType="#//DairyLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionJournals" upperBound="-1"
        eType="#//CollectionJournal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suppliers" ordered="false"
        upperBound="-1" eType="#//Supplier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="animalHealthRequests" upperBound="-1"
        eType="ecore:EClass requests.ecore#//AnimalHealthRequest" containment="true"
        eOpposite="requests.ecore#//AnimalHealthRequest/dairy" eKeys="requests.ecore#//AnimalHealthRequest/requestId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dairyBins" upperBound="-1"
        eType="#//DairyContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="establishedDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Membership">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberId" lowerBound="1"
        eType="ecore:EDataType common.ecore#//UniqueID" iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="memberId"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//MembershipStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultRoute" eType="#//Route"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" lowerBound="1"
        eType="ecore:EClass farm.ecore#//Farmer" containment="true" eKeys="common.ecore#//Person/personId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" eType="#//account/Account"
        eOpposite="#//account/Account/member"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Asset"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eAnnotations source="teneo.jpa">
      <details key="appinfo" value="@Embeddable"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateAcquired" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damageDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damageDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateDisposed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disposalReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disposalWitness" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DairyContainer" eSuperTypes="farm.ecore#//Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assetInfo" eType="#//Asset"
        containment="true" eKeys="#//Asset/tagValue">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="assetInfo"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Embedded"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MembershipStatus">
    <eLiterals name="Active"/>
    <eLiterals name="Inactive" value="1"/>
    <eLiterals name="Dormant" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Session">
    <eLiterals name="EarlyMorning"/>
    <eLiterals name="Morning" value="1"/>
    <eLiterals name="EarlyAfternoon" value="2"/>
    <eLiterals name="Afternoon" value="3"/>
    <eLiterals name="Evening1" value="4"/>
    <eLiterals name="Evening2" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supplier" eSuperTypes="common.ecore#//Company">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplierId" eType="ecore:EDataType common.ecore#//UniqueID">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="supplierId"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categories" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicDescription" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//VendorStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrationDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expirationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VendorStatus">
    <eLiterals name="Pending"/>
    <eLiterals name="Valid" value="1"/>
    <eLiterals name="Invalid" value="2"/>
    <eLiterals name="Suspended" value="3"/>
    <eLiterals name="Other" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DairyFunction">
    <eLiterals name="MilkCollection"/>
    <eLiterals name="MilkStorage" value="1"/>
    <eLiterals name="StoreSales" value="2"/>
    <eLiterals name="Warehouse" value="3"/>
    <eLiterals name="MilkProcessing" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="common.ecore#//Company">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerId" eType="ecore:EDataType common.ecore#//UniqueID">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="customerId"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="account" nsURI="http://com.agritrace.edairy.desktop.common.model/account"
      nsPrefix="account">
    <eClassifiers xsi:type="ecore:EClass" name="Account">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accountId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//Membership"
          eOpposite="#//Membership/account"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="established" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transactions" upperBound="-1"
          eType="#//account/AccountTransaction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="balances" upperBound="-1"
          eType="#//account/BalancePoint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AccountTransaction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactionId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="account" lowerBound="1"
          eType="#//account/Account"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactionType" lowerBound="1"
          eType="#//account/TransactionType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactionDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TransactionType">
      <eLiterals name="CREDIT"/>
      <eLiterals name="DEBIT" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BalancePoint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accountBalanceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="account" lowerBound="1"
          eType="#//account/Account"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="previousBalance" lowerBound="1"
          eType="#//account/BalancePoint"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="asOf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TransactionSource">
      <eLiterals name="StoreCredit" literal="STORE_CREDIT"/>
      <eLiterals name="AnimalHealthServices" value="1" literal="HEALTH_SVCS"/>
      <eLiterals name="ShareRecovery" value="2" literal="SHARE RECOVERY"/>
      <eLiterals name="CashPayment" value="3" literal="CASH PAYMENT"/>
      <eLiterals name="Other" value="4" literal="OTHER"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
