<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tracking"
    nsURI="http://com.agritrace.edairy.desktop.common.model/tracking/" nsPrefix="tracking">
  <eClassifiers xsi:type="ecore:EClass" name="Farm">
    <eOperations name="getNumberOfAnimals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getAnimals().size();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getNumberOfContainers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getCans().size();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="animals" upperBound="-1"
        eType="#//RegisteredAnimal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cans" upperBound="-1" eType="#//Container"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="ecore:EClass common.ecore#//Location"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="farmId" eType="ecore:EDataType common.ecore#//UniqueID"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerId" eType="ecore:EDataType common.ecore#//UniqueID"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Farm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum common.ecore#//ContainerType"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measureType" eType="ecore:EEnum common.ecore#//UnitOfMeasure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegisteredAnimal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrationId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="givenName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Farm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" lowerBound="1"
        eType="ecore:EEnum common.ecore#//Gender" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="animalType" lowerBound="1"
        eType="#//ReferenceAnimalType">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="animalType"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@ManyToOne(cascade=PERSIST)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sireType" eType="#//ReferenceAnimalType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purpose" lowerBound="1"
        eType="#//Purpose" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfAcquisition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acquisitionType" eType="#//AcquisitionType"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifiers" upperBound="-1"
        eType="#//AnimalIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifyingFeatures" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rearingMode" lowerBound="1"
        eType="#//RearingMode" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pastOwners" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfBirth" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthCertificateNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="veterinaryCertificateNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ministryId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insuranceCompany" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feedingHabit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feedType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feedBrand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplements" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="antibiotics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="veterinary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="awards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceAnimalType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="species" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="breed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnimalIdentifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issuer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AcquisitionType">
    <eLiterals name="BIRTH"/>
    <eLiterals name="PURCHASE" value="1"/>
    <eLiterals name="OTHER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Purpose">
    <eLiterals name="DAIRY"/>
    <eLiterals name="BEEF" value="1"/>
    <eLiterals name="BREEDING" value="2"/>
    <eLiterals name="HIDE" value="3"/>
    <eLiterals name="TRANSPORT" value="4"/>
    <eLiterals name="OTHER" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RearingMode">
    <eLiterals name="GRAZE"/>
    <eLiterals name="ZEROGRAZE" value="1"/>
    <eLiterals name="PASTORALHERD" value="2"/>
    <eLiterals name="OTHER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mechanism">
    <eLiterals name="BRAND"/>
    <eLiterals name="BADGE" value="1"/>
    <eLiterals name="COLLAR" value="2"/>
    <eLiterals name="EARTAG" value="3"/>
    <eLiterals name="RFID" value="4"/>
    <eLiterals name="GSMGPRS" value="5"/>
    <eLiterals name="OTHER" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Farmer" eSuperTypes="common.ecore#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="farms" upperBound="-1"
        eType="#//Farm" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
