<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="requests"
    nsURI="http://edairy.agritrace.com/requests/" nsPrefix="requests">
  <eClassifiers xsi:type="ecore:EClass" name="AnimalHealthRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestId" eType="ecore:EDataType common.ecore#//UniqueID"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestingMember" lowerBound="1"
        eType="ecore:EClass dairy.ecore#//Membership"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dairy" lowerBound="1" eType="ecore:EClass dairy.ecore#//Dairy"
        eOpposite="dairy.ecore#//Dairy/animalHealthRequests" eKeys="common.ecore#//Company/companyId">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="dairy"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@ManyToOne(cascade=PERSIST)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RequestType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reportedProblem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportedAnimal" eType="ecore:EClass farm.ecore#//RegisteredAnimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateHeatDetected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstTreatment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondTreatment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thirdTreatment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="farm" lowerBound="1" eType="ecore:EClass farm.ecore#//Farm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredTo" eType="ecore:EClass dairy.ecore#//Supplier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequestType">
    <eLiterals name="Clinical" literal="Clinical"/>
    <eLiterals name="Insemination" value="1" literal="A.I."/>
  </eClassifiers>
</ecore:EPackage>
