package com.agritrace.edairy.desktop.collection.ui;

public interface ViewConstants {

	// collection dialog
	String DRIVER = "driver";
	String VEHICLE = "vehicle";
	String REFERENCE_NUMBER = "referenceNumber";
	String ROUTE = "route";
	String SESSION = "session";
	String DATE_PICKER = "date-picker";

	String COLLECTION_DETAIL_BACK_BTN = "COLLECTION_DETAIL_BACK_BTN";
	String COLLECTION_DETAIL_EDIT_BTN = "COLLECTION_DETAIL_EDIT_BTN";
	String COLLECTION_DETAIL_FILTER_BTN = "COLLECTION_DETAIL_FILTER_BTN";
	String COLLECTION_DETAIL_FILTER_PAGE_SPIN = "COLLECTION_DETAIL_FILTER_PAGE_SPIN";
	String COLLECTION_DETAIL_HEADER_BOOK_TXT = "COLLECTION_DETAIL_HEADER_BOOK_TXT";
	// collection detail log
	String COLLECTION_DETAIL_HEADER_DATE_TXT = "COLLECTION_DETAIL_HEADER_DATE_TXT";

	String COLLECTION_DETAIL_HEADER_DRIVER_TXT = "COLLECTION_DETAIL_HEADER_DRIVER_TXT";
	String COLLECTION_DETAIL_HEADER_ROUTE_TXT = "COLLECTION_DETAIL_HEADER_ROUTE_TXT";
	String COLLECTION_DETAIL_HEADER_SESSION_TXT = "COLLECTION_DETAIL_HEADER_SESSION_TXT";
	String COLLECTION_DETAIL_HEADER_VEHICLE_TXT = "COLLECTION_DETAIL_HEADER_VEHICLE_TXT";
	String COLLECTION_DETAIL_NEW_BTN = "COLLECTION_DETAIL_NEW_BTN";
	
	String COLLECTION_FILTER_END_DATE_TEXT = "COLLECTION_FILTER_END_DATE_TEXT";
	String COLLECTION_FILTER_MPR_MISSING_CHK = "COLLECTION_FILTER_MPR_MISSING_CHK";
	String COLLECTION_FILTER_REJECTED_CHK = "COLLECTION_FILTER_REJECTED_CHK";
	String COLLECTION_FILTER_ROUTE_COMBO = "COLLECTION_FILTER_ROUTE_COMBO";
	// collection log
	String COLLECTION_FILTER_START_DATE_TEXT = "COLLECTION_FILTER_START_DATE_TEXT";
	String COLLECTION_FILTER_SUSPENDED_CHK = "COLLECTION_FILTER_SUSPENDED_CHK";
	String COLLECTION_FILTER_STATUS_COMBO = "COLLECTION_FILTER_STATUS_COMBO";
	String COLLECTION_FILTER_SESSION_COMBO = "COLLECTION_FILTER_SESSION_COMBO";

	//

}
