package com.agritrace.edairy.desktop.common.model.dairy.security;

/**
 * Represents a security permission namespace. Not autogenerated.
 *
 * @author Matvey Kozhev <inetperson@gmail.com>
 *
 */
public enum Namespace {
	MILK("Milk"),
	MEMBERSHIP("Membership"),
	FINANCE("Finance"),
	CLINICAL("Clinical"),
	OPERATIONS("Operations"),
	SYSTEM("System");

	private String name;

	private Namespace(String name) {
		this.name = name;
	}

	/**
	 * Returns the human-readable display name of the namespace, like "Membership".
	 */
	@Override
	public String toString() {
		return name;
	}
}
