package com.agritrace.edairy.desktop.finance.ui;

public interface FinanceBindingConstants {
	static final String DESC_TEXT = "descText";
	static final String RECORD_ID_TEXT = "recordIdText";
	static final String FILTER_CHOICE_TX_TYPE = "FILTER_CHOICE_TX_TYPE";
	static final String FILTER_SOURCE_ROW = "FILTER_SOURCE_ROW";
	static final String FILTER_TYPE_ROW = "FILTER_TYPE_ROW";
	static final String ID_COMBO_ADJUSTMENT_TYPE = "ID_COMBO_ADJUSTMENT_TYPE";
	static final String FILTER_DATE_RANGE = "FILTER_DATE_RANGE";
	static final String FILTER_MEMBER_LOOKUP_BTN = "FILTER_MEMBER_LOOKUP_BTN";
	static final String ID_SIGNED_BY_TEXT_LBL = "ID_SIGNED_BY_TEXT_LBL";
	static final String ID_DAIRY_LOCATION_COMBO_LBL = "ID_DAIRY_LOCATION_COMBO_LBL";
	static final String ID_CHECK_NUMBER_TEXT_LBL = "ID_CHECK_NUMBER_TEXT_LBL";
	static final String BTN_RUN_PAYMENTS = "BTN_RUN_PAYMENTS";
	static final String TABLE = "TABLE";

	String AMT_TEXT_RIDGET = "amtText";
	String BTN_ADD_TRANSACTION = "btnAddTransaction";
	String BTN_CANCEL_ALL = "btnCancelAll";
	String BTN_CLEAR_CURRENT = "btnClearCurrent";
	String BTN_DELETE = "btnDelete";

	// from Form
	String BTN_SAVE_ALL_RECORDS = "btnSaveAllRecords";

	String BTN_VIEW = "btnView";
	String CHK_NO_TEXT_RIDGET = "chkNoText";
	String DETAIL_TABLE_RIDGET = "detailTable";
	String FILTER_CHOICE_TX_SOURCE = "FILTER_CHOICE_TX_SOURCE";

	String FILTER_COMBO_STORE = "FILTER_COMBO_STORE";
	String FILTER_DATE_END_DATE = "FILTER_COMBO_END_DATE";
	String FILTER_DATE_START_DATE = "FILTER_COMBO_START_DATE";
	String FILTER_MEMBER_LOOKUP_TXT = "FILTER_TXT_MEMBER_LOOKUP";
	String FILTER_TXT_REF_NO = "FILTER_TXT_REF_NO";
	String GRP_TRANSACTIONS_TBLLABEL = "grpTransactions";
	// from ViewConstants
	String ID_BTN_BATCH_ENTRY = "ID_BTN_BATCH_ENTRY";
	String ID_CHECK_NUMBER_TEXT = "CHECK_NUMBER_TEXT";
	String ID_DAIRY_LOCATION_COMBO = "DAIRY_LOCATION_COMBO";
	String ID_DAIRY_LOCATION_TEXT = "DAIRY_LOCATION_TEXT";
	String ID_LOOKUP_BTN = "MEMBER_LOOKUP_BTN";

	String ID_LOOKUP_RESULT_TXT = "MEMBER_NAME_TEXT";
	String ID_PAYMENT_CHOICEBTN = "PAYMENT_BTN";
	String ID_RECORD_ID_TEXT = "RECORD_ID_TEXT";
	String ID_REF_NUMBER_TEXT = "REF_NUMBER_TEXT";
	String ID_SHARE_DEDUCTION_CHOICEBTN = "SHARE_DEDUCTION_BTN";
	String ID_SIGNED_BY_TEXT = "SIGNED_BY_TEXT";
	String ID_STORE_SALE_CHOICEBTN = "STORE_SALE_BTN";
	String ID_TRANSACTION_WRAPPER_FRAME = "TRANSACTION_WRAPPER_FRAME";
	String ID_TRANSACTION_ALERT_FRAME = "TRANSACTION_ALERT_FRAME";
	String ID_TRANSACTION_AMOUNT_TEXT = "TRANSACTION_AMOUNT_TEXT";
	// member transaction edit panel
	String ID_TRANSACTION_CHOICE = "TRANSACTION_CHOICE";
	String ID_TRANSACTION_DATE = "TRANSACTION_DATE";
	String ID_TRANSACTION_DESCRIPTION_TEXT = "TRANSACTION_DESCRIPTION_TEXT";
	String ID_VETERINARY_CHOICEBTN = "VETERINARY_BTN";

	String LBL_MEMBER_NAME_RIDGET = "lblMemberName";
	String SIGNED_BY_TEXT_RIDGET = "signedByText";

}
