package com.agritrace.edairy.desktop.operations.ui.dialogs;

public interface EmployeeBindingConstants {

	String BIND_ID_DEPARTMENT = "BIND_ID_DEPARTMENT";
	String BIND_ID_EMPLOYEE_ID = "BIND_ID_EMPLOYEE_ID";
	String BIND_ID_FAMILY_NAME = "BIND_ID_FAMILY_NAME";
	String BIND_ID_GIVEN_NAME = "BIND_ID_GIVEN_NAME";
	String BIND_ID_POSITION = "BIND_ID_POSITION";
	String BIND_ID_EMPLOYEE_NUM = "BIND_ID_EMPLOYEE_NUM";
	String BIND_ID_OPR_CODE = "BIND_ID_OPR_CODE";
	String BIND_ID_SEC_ROLE = "BIND_ID_SEC_ROLE";
	String BIND_ID_SINCE = "BIND_ID_SINCE";
	String BIND_ID_USERNAME = "BIND_ID_USERNAME";
	String BIND_ID_PASSWORD = "BIND_ID_PASSWORD";
	String BIND_ID_LOCAL_ENABLED = "BIND_ID_LOCAL_ENABLED";
}
