SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
SHOW WARNINGS;
CREATE SCHEMA IF NOT EXISTS `jdev` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`CONTAINER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`CONTAINER` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`CONTAINER` (
  `CONTAINERID` BIGINT(20) NOT NULL ,
  `DTYPE` VARCHAR(31) NULL DEFAULT NULL ,
  `CAPACITY` DOUBLE NULL DEFAULT NULL ,
  `UNITS` DOUBLE NULL DEFAULT NULL ,
  `BINID` BIGINT(20) NULL DEFAULT NULL ,
  `COLLECTIONCENTRE_COLLECTIONCENTREID` BIGINT(20) NULL DEFAULT NULL ,
  `ROUTE_ROUTEID` BIGINT(20) NULL DEFAULT NULL ,
  PRIMARY KEY (`CONTAINERID`) ,
  INDEX `FK_CONTAINER_ROUTE_ROUTEID` (`ROUTE_ROUTEID` ASC) ,
  INDEX `FK_CONTAINER_COLLECTIONCENTRE_COLLECTIONCENTREID` (`COLLECTIONCENTRE_COLLECTIONCENTREID` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`DAIRY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`DAIRY` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`DAIRY` (
  `DAIRYID` BIGINT(20) NOT NULL ,
  `TRANSACTIONSOURCES` BLOB NULL DEFAULT NULL ,
  `NHIFNUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `KDBLICENSENUM` VARCHAR(45) NULL DEFAULT NULL ,
  `NSSFNUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `PUBLICDESCRIPTION` VARCHAR(45) NULL DEFAULT NULL ,
  `PIN` VARCHAR(45) NULL DEFAULT NULL ,
  `KDBLICENSEEXPIRATIONDATE` DATE NULL DEFAULT NULL ,
  `KDBLICENSEEFFECTIVEDATE` DATE NULL DEFAULT NULL ,
  `NAME` VARCHAR(45) NULL DEFAULT NULL ,
  `MANAGER_EMPLOYMENTRELATIONSHIPID` BIGINT(20) NULL DEFAULT NULL ,
  `LATITUDE` DOUBLE NULL DEFAULT NULL ,
  `DIVISION` VARCHAR(45) NULL DEFAULT NULL ,
  `SUBLOCATION` VARCHAR(45) NULL DEFAULT NULL ,
  `LOCATIONDIRECTIONS` VARCHAR(45) NULL DEFAULT NULL ,
  `LANDREFERENCENUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `TAG` VARCHAR(45) NULL DEFAULT NULL ,
  `ADDRESS` VARCHAR(45) NULL DEFAULT NULL ,
  `VILLAGE` VARCHAR(45) NULL DEFAULT NULL ,
  `POSTALCODE` VARCHAR(45) NULL DEFAULT NULL ,
  `LONGITUDE` DOUBLE NULL DEFAULT NULL ,
  `SECTION` VARCHAR(45) NULL DEFAULT NULL ,
  `ESTATE` VARCHAR(45) NULL DEFAULT NULL ,
  `LOCATION` VARCHAR(45) NULL DEFAULT NULL ,
  `LANDMARKLOCATIONS` VARCHAR(45) NULL DEFAULT NULL ,
  `DISTRICT` VARCHAR(45) NULL DEFAULT NULL ,
  `CONTAINER_CONTAINERID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`DAIRYID`) ,
  INDEX `FK_DAIRY_MANAGER_EMPLOYMENTRELATIONSHIPID` (`MANAGER_EMPLOYMENTRELATIONSHIPID` ASC) ,
  INDEX `fk_DAIRY_CONTAINER1` (`CONTAINER_CONTAINERID` ASC) ,
  CONSTRAINT `fk_DAIRY_CONTAINER1`
    FOREIGN KEY (`CONTAINER_CONTAINERID` )
    REFERENCES `jdev`.`CONTAINER` (`CONTAINERID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`PERSON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`PERSON` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`PERSON` (
  `PERSONID` BIGINT(20) NOT NULL ,
  `MIDDLENAME` VARCHAR(45) NULL DEFAULT NULL ,
  `ADDITIONALNAMES` BLOB NULL DEFAULT NULL ,
  `HONORIFIC` VARCHAR(45) NULL DEFAULT NULL ,
  `FAMILYNAME` VARCHAR(45) NULL DEFAULT NULL ,
  `GIVEN_NAME` VARCHAR(45) NULL DEFAULT NULL ,
  `SUFFIX` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`PERSONID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`MEMBERSHIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`MEMBERSHIP` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`MEMBERSHIP` (
  `MEMBERSHIPID` INT(11) NOT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `PERSON_PERSONID` BIGINT(20) NOT NULL ,
  `APPLICATIONDATE` DATE NULL DEFAULT NULL ,
  `EFFECTIVEDATE` DATE NULL DEFAULT NULL ,
  `STATUS` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`MEMBERSHIPID`) ,
  INDEX `fk_MEMBERSHIP_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_MEMBERSHIP_PERSON1` (`PERSON_PERSONID` ASC) ,
  CONSTRAINT `fk_MEMBERSHIP_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEMBERSHIP_PERSON1`
    FOREIGN KEY (`PERSON_PERSONID` )
    REFERENCES `jdev`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`ACCOUNT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`ACCOUNT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`ACCOUNT` (
  `ACCOUNTID` BIGINT(20) NOT NULL ,
  `MEMBERSHIP_MEMBERSHIPID` INT(11) NOT NULL ,
  `ESTABLISHED` DATE NULL DEFAULT NULL ,
  `TYPE` VARCHAR(45) NULL DEFAULT NULL ,
  `MEMBERSHIP_DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`ACCOUNTID`) ,
  INDEX `fk_ACCOUNT_MEMBERSHIP1` (`MEMBERSHIP_MEMBERSHIPID` ASC, `MEMBERSHIP_DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_ACCOUNT_MEMBERSHIP1`
    FOREIGN KEY (`MEMBERSHIP_MEMBERSHIPID` , `MEMBERSHIP_DAIRY_DAIRYID` )
    REFERENCES `jdev`.`MEMBERSHIP` (`MEMBERSHIPID` , `DAIRY_DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`ACCOUNTTRANSACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`ACCOUNTTRANSACTION` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`ACCOUNTTRANSACTION` (
  `TRANSACTIONID` BIGINT(20) NOT NULL ,
  `AMOUNT` DECIMAL(38,0) NULL DEFAULT NULL ,
  `SOURCE` VARCHAR(45) NULL DEFAULT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL ,
  `TYPE` INT(11) NULL DEFAULT NULL ,
  `ACCOUNT_ACCOUNTID` BIGINT(20) NULL DEFAULT NULL ,
  `ACCOUNT_ACCOUNTID1` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`TRANSACTIONID`) ,
  INDEX `FK_ACCOUNTTRANSACTION_ACCOUNT_ACCOUNTID` (`ACCOUNT_ACCOUNTID` ASC) ,
  INDEX `fk_ACCOUNTTRANSACTION_ACCOUNT1` (`ACCOUNT_ACCOUNTID1` ASC) ,
  CONSTRAINT `fk_ACCOUNTTRANSACTION_ACCOUNT1`
    FOREIGN KEY (`ACCOUNT_ACCOUNTID1` )
    REFERENCES `jdev`.`ACCOUNT` (`ACCOUNTID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`FARM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`FARM` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`FARM` (
  `FARMID` INT(11) NOT NULL ,
  `NAME` VARCHAR(45) NULL DEFAULT NULL ,
  `PERSON_PERSONID` BIGINT(20) NOT NULL ,
  `LICENSENUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `DEFAULTCOLLECTIONCENTER_COLLECTIONCENTREID` BIGINT(20) NULL DEFAULT NULL ,
  `LATITUDE` DOUBLE NULL DEFAULT NULL ,
  `DIVISION` VARCHAR(45) NULL DEFAULT NULL ,
  `SUBLOCATION` VARCHAR(45) NULL DEFAULT NULL ,
  `LOCATIONDIRECTIONS` VARCHAR(45) NULL DEFAULT NULL ,
  `LANDREFERENCENUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `TAG` VARCHAR(45) NULL DEFAULT NULL ,
  `ADDRESS` VARCHAR(45) NULL DEFAULT NULL ,
  `VILLAGE` VARCHAR(45) NULL DEFAULT NULL ,
  `POSTALCODE` VARCHAR(45) NULL DEFAULT NULL ,
  `LONGITUDE` DOUBLE NULL DEFAULT NULL ,
  `SECTION` VARCHAR(45) NULL DEFAULT NULL ,
  `ESTATE` VARCHAR(45) NULL DEFAULT NULL ,
  `LOCATION` VARCHAR(45) NULL DEFAULT NULL ,
  `LANDMARKLOCATIONS` VARCHAR(45) NULL DEFAULT NULL ,
  `DISTRICT` VARCHAR(45) NULL DEFAULT NULL ,
  `CONTAINER_CONTAINERID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`FARMID`) ,
  INDEX `FK_FARM_DEFAULTCOLLECTIONCENTER_COLLECTIONCENTREID` (`DEFAULTCOLLECTIONCENTER_COLLECTIONCENTREID` ASC) ,
  INDEX `fk_FARM_PERSON1` (`PERSON_PERSONID` ASC) ,
  INDEX `fk_FARM_CONTAINER1` (`CONTAINER_CONTAINERID` ASC) ,
  CONSTRAINT `fk_FARM_PERSON1`
    FOREIGN KEY (`PERSON_PERSONID` )
    REFERENCES `jdev`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FARM_CONTAINER1`
    FOREIGN KEY (`CONTAINER_CONTAINERID` )
    REFERENCES `jdev`.`CONTAINER` (`CONTAINERID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`REFERENCEANIMALTYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`REFERENCEANIMALTYPE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`REFERENCEANIMALTYPE` (
  `ANIMALTYPEID` BIGINT(20) NOT NULL ,
  `BREED` VARCHAR(45) NULL DEFAULT NULL ,
  `SPECIES` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`ANIMALTYPEID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`REGISTEREDANIMAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`REGISTEREDANIMAL` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`REGISTEREDANIMAL` (
  `ANIMNALREGISTRATIONID` BIGINT(20) NOT NULL ,
  `INSURANCENUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `IDENTIFIERS` BLOB NULL DEFAULT NULL ,
  `GIVENNAME` VARCHAR(45) NOT NULL ,
  `PURPOSE` INT(11) NOT NULL ,
  `PASTOWNERS` BLOB NULL DEFAULT NULL ,
  `ACQUISITIONTYPE` INT(11) NULL DEFAULT NULL ,
  `IDENTIFYINGFEATURES` VARCHAR(45) NULL DEFAULT NULL ,
  `REARINGMODE` INT(11) NULL DEFAULT NULL ,
  `GENDER` INT(11) NOT NULL ,
  `DATEOFACQUISITION` DATE NOT NULL ,
  `LOCATION_FARMID` INT(11) NULL DEFAULT NULL ,
  `ANIMALTYPE__ANIMALTYPEID` BIGINT(20) NULL DEFAULT NULL ,
  `SIRETYPE__ANIMALTYPEID` BIGINT(20) NULL DEFAULT NULL ,
  `FARM_FARMID` INT(11) NOT NULL ,
  `REFERENCEANIMALTYPE__ANIMALTYPEID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`ANIMNALREGISTRATIONID`) ,
  INDEX `FK_REGISTEREDANIMAL_SIRETYPE__ANIMALTYPEID` (`SIRETYPE__ANIMALTYPEID` ASC) ,
  INDEX `FK_REGISTEREDANIMAL_LOCATION_FARMID` (`LOCATION_FARMID` ASC) ,
  INDEX `FK_REGISTEREDANIMAL_ANIMALTYPE__ANIMALTYPEID` (`ANIMALTYPE__ANIMALTYPEID` ASC) ,
  INDEX `fk_REGISTEREDANIMAL_FARM1` (`FARM_FARMID` ASC) ,
  INDEX `fk_REGISTEREDANIMAL_REFERENCEANIMALTYPE1` (`REFERENCEANIMALTYPE__ANIMALTYPEID` ASC) ,
  CONSTRAINT `fk_REGISTEREDANIMAL_FARM1`
    FOREIGN KEY (`FARM_FARMID` )
    REFERENCES `jdev`.`FARM` (`FARMID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REGISTEREDANIMAL_REFERENCEANIMALTYPE1`
    FOREIGN KEY (`REFERENCEANIMALTYPE__ANIMALTYPEID` )
    REFERENCES `jdev`.`REFERENCEANIMALTYPE` (`ANIMALTYPEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`ANIMALHISTORYRECORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`ANIMALHISTORYRECORD` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`ANIMALHISTORYRECORD` (
  `ANIMALHISTORYRECORDID` BIGINT(20) NOT NULL ,
  `NEWSTATUS` INT(11) NULL DEFAULT NULL ,
  `NEWSTATUSDATE` DATE NULL DEFAULT NULL ,
  `STATUSINFO` VARCHAR(45) NULL DEFAULT NULL ,
  `REGISTRATIONID_ANIMNALREGISTRATIONID` BIGINT(20) NULL DEFAULT NULL ,
  `REGISTEREDANIMAL_ANIMNALREGISTRATIONID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`ANIMALHISTORYRECORDID`) ,
  INDEX `NMALHISTORYRECORDRGSTRATIONIDANIMNALREGISTRATIONID` (`REGISTRATIONID_ANIMNALREGISTRATIONID` ASC) ,
  INDEX `fk_ANIMALHISTORYRECORD_REGISTEREDANIMAL1` (`REGISTEREDANIMAL_ANIMNALREGISTRATIONID` ASC) ,
  CONSTRAINT `fk_ANIMALHISTORYRECORD_REGISTEREDANIMAL1`
    FOREIGN KEY (`REGISTEREDANIMAL_ANIMNALREGISTRATIONID` )
    REFERENCES `jdev`.`REGISTEREDANIMAL` (`ANIMNALREGISTRATIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`BALANCEPOINT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`BALANCEPOINT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`BALANCEPOINT` (
  `ACCOUNTBALANCEID` BIGINT(20) NOT NULL ,
  `ACCOUNT_ACCOUNTID` BIGINT(20) NOT NULL ,
  `PREVIOUS_BALANCEPOINT` BIGINT(20) NULL DEFAULT NULL ,
  `AMOUNT` DECIMAL(38,0) NULL DEFAULT NULL ,
  `ASOF` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`ACCOUNTBALANCEID`) ,
  INDEX `fk_BALANCEPOINT_BALANCEPOINT1` (`PREVIOUS_BALANCEPOINT` ASC) ,
  INDEX `fk_BALANCEPOINT_ACCOUNT1` (`ACCOUNT_ACCOUNTID` ASC) ,
  CONSTRAINT `fk_BALANCEPOINT_BALANCEPOINT1`
    FOREIGN KEY (`PREVIOUS_BALANCEPOINT` )
    REFERENCES `jdev`.`BALANCEPOINT` (`ACCOUNTBALANCEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BALANCEPOINT_ACCOUNT1`
    FOREIGN KEY (`ACCOUNT_ACCOUNTID` )
    REFERENCES `jdev`.`ACCOUNT` (`ACCOUNTID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`COLLECTIONJOURNAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`COLLECTIONJOURNAL` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`COLLECTIONJOURNAL` (
  `ID` BIGINT(20) NOT NULL ,
  `JOURNALTOTAL` DECIMAL(38,0) NULL DEFAULT NULL ,
  `SESSION` VARCHAR(45) NULL DEFAULT NULL ,
  `REFERENCENUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `FLAGGED` TINYINT(1) NULL DEFAULT '0' ,
  `JOURNALDATE` DATE NULL DEFAULT NULL ,
  `ENTRYDATE` DATE NULL DEFAULT NULL ,
  `ROUTE_ROUTEID` BIGINT(20) NULL DEFAULT NULL ,
  `VEHICLE_VEHICLEID` BIGINT(20) NULL DEFAULT NULL ,
  `DRIVER_EMPLOYMENTRELATIONSHIPID` BIGINT(20) NULL DEFAULT NULL ,
  `ENTRYCLERK_EMPLOYMENTRELATIONSHIPID` BIGINT(20) NULL DEFAULT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_COLLECTIONJOURNAL_ROUTE_ROUTEID` (`ROUTE_ROUTEID` ASC) ,
  INDEX `COLLECTIONJOURNAL_DRIVER_EMPLOYMENTRELATIONSHIPID` (`DRIVER_EMPLOYMENTRELATIONSHIPID` ASC) ,
  INDEX `COLLECTIONJOURNALNTRYCLERKEMPLOYMENTRELATIONSHIPID` (`ENTRYCLERK_EMPLOYMENTRELATIONSHIPID` ASC) ,
  INDEX `FK_COLLECTIONJOURNAL_VEHICLE_VEHICLEID` (`VEHICLE_VEHICLEID` ASC) ,
  INDEX `fk_COLLECTIONJOURNAL_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_COLLECTIONJOURNAL_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`COLLECTIONRECORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`COLLECTIONRECORD` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`COLLECTIONRECORD` (
  `COLLECTIONRECORDID` BIGINT(20) NOT NULL ,
  `RECORDEDMEMBERID` VARCHAR(45) NULL DEFAULT NULL ,
  `OFFROUTE` TINYINT(1) NULL DEFAULT '0' ,
  `QUANTITYCOLLECTED` DECIMAL(38,0) NULL DEFAULT NULL ,
  `REJECTED` TINYINT(1) NULL DEFAULT '0' ,
  `NOTRECORDED` TINYINT(1) NULL DEFAULT '0' ,
  `JOURNALSEQUENCE` INT(11) NULL DEFAULT NULL ,
  `SUSPENDED` TINYINT(1) NULL DEFAULT '0' ,
  `COLLECTIONJOURNAL_ID` BIGINT(20) NULL DEFAULT NULL ,
  `CAN_CONTAINERID` BIGINT(20) NULL DEFAULT NULL ,
  `COLLECTIONJOURNAL_ID1` BIGINT(20) NOT NULL ,
  `COLLECTIONJOURNAL_DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`COLLECTIONRECORDID`) ,
  INDEX `FK_COLLECTIONRECORD_COLLECTIONJOURNAL_ID` (`COLLECTIONJOURNAL_ID` ASC) ,
  INDEX `FK_COLLECTIONRECORD_CAN_CONTAINERID` (`CAN_CONTAINERID` ASC) ,
  INDEX `fk_COLLECTIONRECORD_COLLECTIONJOURNAL1` (`COLLECTIONJOURNAL_ID1` ASC, `COLLECTIONJOURNAL_DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_COLLECTIONRECORD_COLLECTIONJOURNAL1`
    FOREIGN KEY (`COLLECTIONJOURNAL_ID1` , `COLLECTIONJOURNAL_DAIRY_DAIRYID` )
    REFERENCES `jdev`.`COLLECTIONJOURNAL` (`ID` , `DAIRY_DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`CONTACTMETHOD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`CONTACTMETHOD` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`CONTACTMETHOD` (
  `CONTACTMETHODID` BIGINT(20) NOT NULL ,
  `CONTACTINFO` VARCHAR(45) NULL DEFAULT NULL ,
  `CONTACTTYPE` INT(11) NULL DEFAULT NULL ,
  `PERSON_PERSONID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`CONTACTMETHODID`) ,
  INDEX `fk_CONTACTMETHOD_PERSON1` (`PERSON_PERSONID` ASC) ,
  CONSTRAINT `fk_CONTACTMETHOD_PERSON1`
    FOREIGN KEY (`PERSON_PERSONID` )
    REFERENCES `jdev`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`ROUTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`ROUTE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`ROUTE` (
  `ROUTEID` BIGINT(20) NOT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL ,
  `NAME` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`ROUTEID`) ,
  INDEX `fk_ROUTE_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_ROUTE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`DAIRYLOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`DAIRYLOCATION` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`DAIRYLOCATION` (
  `DAIRYLOCATIONID` BIGINT(20) NOT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `ROUTE_ROUTEID` BIGINT(20) NOT NULL ,
  `DATEOPENED` DATE NULL DEFAULT NULL ,
  `PHONENUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL ,
  `NAME` VARCHAR(45) NULL DEFAULT NULL ,
  `COLORCODE` VARCHAR(45) NULL DEFAULT NULL ,
  `FUNCTION` INT(11) NULL DEFAULT NULL ,
  `LATITUDE` DOUBLE NULL DEFAULT NULL ,
  `DIVISION` VARCHAR(45) NULL DEFAULT NULL ,
  `SUBLOCATION` VARCHAR(45) NULL DEFAULT NULL ,
  `LOCATIONDIRECTIONS` VARCHAR(45) NULL DEFAULT NULL ,
  `LANDREFERENCENUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `TAG` VARCHAR(45) NULL DEFAULT NULL ,
  `ADDRESS` VARCHAR(45) NULL DEFAULT NULL ,
  `VILLAGE` VARCHAR(45) NULL DEFAULT NULL ,
  `POSTALCODE` VARCHAR(45) NULL DEFAULT NULL ,
  `LONGITUDE` DOUBLE NULL DEFAULT NULL ,
  `SECTION` VARCHAR(45) NULL DEFAULT NULL ,
  `ESTATE` VARCHAR(45) NULL DEFAULT NULL ,
  `LOCATION` VARCHAR(45) NULL DEFAULT NULL ,
  `LANDMARKLOCATIONS` VARCHAR(45) NULL DEFAULT NULL ,
  `DISTRICT` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`DAIRYLOCATIONID`) ,
  INDEX `fk_DAIRYLOCATION_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_DAIRYLOCATION_ROUTE1` (`ROUTE_ROUTEID` ASC) ,
  CONSTRAINT `fk_DAIRYLOCATION_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DAIRYLOCATION_ROUTE1`
    FOREIGN KEY (`ROUTE_ROUTEID` )
    REFERENCES `jdev`.`ROUTE` (`ROUTEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`DOMAINELEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`DOMAINELEMENT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`DOMAINELEMENT` (
  `DOMAINELEMENTID` BIGINT(20) NOT NULL ,
  `ELEMENTCODE` VARCHAR(45) NULL DEFAULT NULL ,
  `ELEMENTNAME` VARCHAR(45) NULL DEFAULT NULL ,
  `ELEMENTDESCRIPTION` VARCHAR(45) NULL DEFAULT NULL ,
  `DOMAINNAME` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`DOMAINELEMENTID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`ROLE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`ROLE` (
  `SECURITYROLEID` BIGINT(20) NOT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL ,
  `SYSTEMDEFINED` TINYINT(1) NULL DEFAULT '0' ,
  `NAME` VARCHAR(45) NULL DEFAULT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`SECURITYROLEID`) ,
  INDEX `fk_SECURITYROLE_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_SECURITYROLE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`EMPLOYEE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`EMPLOYEE` (
  `EMPLOYMENTRELATIONSHIPID` BIGINT(20) NOT NULL ,
  `DTYPE` VARCHAR(31) NULL DEFAULT NULL ,
  `STARTDATE` DATE NULL DEFAULT NULL ,
  `PREVIOUSEMPID` BIGINT(20) NULL DEFAULT NULL ,
  `ENDDATE` DATE NULL DEFAULT NULL ,
  `JOBFUNCTION` VARCHAR(45) NULL DEFAULT NULL ,
  `EMPLOYEE_PERSONID` BIGINT(20) NULL DEFAULT NULL ,
  `ENCRYPTEDPASSWORD` VARCHAR(45) NULL DEFAULT NULL ,
  `USERNAME` VARCHAR(45) NULL DEFAULT NULL ,
  `SYSTEMUSERID` BIGINT(20) NULL DEFAULT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `PERSON_PERSONID` BIGINT(20) NOT NULL ,
  `SECURITYROLE_SECURITYROLEID` BIGINT(20) NOT NULL ,
  `SECURITYROLE_DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`EMPLOYMENTRELATIONSHIPID`) ,
  INDEX `FK_EMPLOYEE_EMPLOYEE_PERSONID` (`EMPLOYEE_PERSONID` ASC) ,
  INDEX `fk_EMPLOYEE_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_EMPLOYEE_PERSON1` (`PERSON_PERSONID` ASC) ,
  INDEX `fk_EMPLOYEE_SECURITYROLE1` (`SECURITYROLE_SECURITYROLEID` ASC, `SECURITYROLE_DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_EMPLOYEE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_PERSON1`
    FOREIGN KEY (`PERSON_PERSONID` )
    REFERENCES `jdev`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_SECURITYROLE1`
    FOREIGN KEY (`SECURITYROLE_SECURITYROLEID` , `SECURITYROLE_DAIRY_DAIRYID` )
    REFERENCES `jdev`.`ROLE` (`SECURITYROLEID` , `DAIRY_DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`LOGINHISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`LOGINHISTORY` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`LOGINHISTORY` (
  `LOGINHISTORYID` BIGINT(20) NOT NULL ,
  `EMPLOYEE_EMPLOYMENTRELATIONSHIPID` BIGINT(20) NOT NULL ,
  `EMPLOYEE_DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `TIMESTAMP` DATETIME NOT NULL ,
  `IPADDRESS` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`LOGINHISTORYID`) ,
  INDEX `fk_LOGINHISTORY_EMPLOYEE1` (`EMPLOYEE_EMPLOYMENTRELATIONSHIPID` ASC, `EMPLOYEE_DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_LOGINHISTORY_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_EMPLOYMENTRELATIONSHIPID` , `EMPLOYEE_DAIRY_DAIRYID` )
    REFERENCES `jdev`.`EMPLOYEE` (`EMPLOYMENTRELATIONSHIPID` , `DAIRY_DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`MILKPRICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`MILKPRICE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`MILKPRICE` (
  `PRICEID` BIGINT(20) NOT NULL ,
  `PRICEDATE` DATE NULL DEFAULT NULL ,
  `PRICE` DECIMAL(38,0) NULL DEFAULT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `DAIRY_CONTAINER_CONTAINERID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`PRICEID`) ,
  INDEX `fk_MILKPRICE_DAIRY1` (`DAIRY_DAIRYID` ASC, `DAIRY_CONTAINER_CONTAINERID` ASC) ,
  CONSTRAINT `fk_MILKPRICE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` , `DAIRY_CONTAINER_CONTAINERID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` , `CONTAINER_CONTAINERID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`SEQUENCE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`SEQUENCE` (
  `SEQ_NAME` VARCHAR(50) NOT NULL ,
  `SEQ_COUNT` DECIMAL(38,0) NULL DEFAULT NULL ,
  PRIMARY KEY (`SEQ_NAME`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`SUPPLIER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`SUPPLIER` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`SUPPLIER` (
  `SUPPLIERID` BIGINT(20) NOT NULL ,
  `CATEGORY` VARCHAR(45) NULL DEFAULT NULL ,
  `STATUS` INT(11) NULL DEFAULT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL ,
  `NAME` VARCHAR(45) NULL DEFAULT NULL ,
  `EFFECTIVEDATE` DATE NULL DEFAULT NULL ,
  `CONTRACTDURATION` BIGINT(20) NULL DEFAULT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `PERSON_PERSONID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`SUPPLIERID`) ,
  INDEX `fk_SUPPLIER_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_SUPPLIER_PERSON1` (`PERSON_PERSONID` ASC) ,
  CONSTRAINT `fk_SUPPLIER_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUPPLIER_PERSON1`
    FOREIGN KEY (`PERSON_PERSONID` )
    REFERENCES `jdev`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`VEHICLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`VEHICLE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`VEHICLE` (
  `VEHICLEID` BIGINT(20) NOT NULL ,
  `MODEL` VARCHAR(45) NULL DEFAULT NULL ,
  `DOMINANTCOLOUR` VARCHAR(45) NULL DEFAULT NULL ,
  `INSURANCEPOLICYNUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `CHASSISNUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `TYPE` VARCHAR(45) NULL DEFAULT NULL ,
  `ENGINENUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `REGISTRATIONNUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `LOGBOOKNUMBER` VARCHAR(45) NULL DEFAULT NULL ,
  `INSURANCEPURCHASEDATE` DATE NULL DEFAULT NULL ,
  `CAPACITYINTONNES` DOUBLE NULL DEFAULT NULL ,
  `MODELYEAR` INT(11) NULL DEFAULT NULL ,
  `MAKE` VARCHAR(45) NULL DEFAULT NULL ,
  `ASSETID` BIGINT(20) NULL DEFAULT NULL ,
  `PURCHASEDATE` DATE NOT NULL ,
  `DISPOSALMETHOD` VARCHAR(45) NULL DEFAULT NULL ,
  `DISPOSALDATE` DATE NULL DEFAULT NULL ,
  `WITNESS` VARCHAR(45) NULL DEFAULT NULL ,
  `DAMAGEDATE` DATE NULL DEFAULT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`VEHICLEID`) ,
  INDEX `fk_VEHICLE_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_VEHICLE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `jdev`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`PERMISSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`PERMISSION` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`PERMISSION` (
  `PERMISSIONID` BIGINT(20) NOT NULL ,
  `SHORTNAME` VARCHAR(45) NULL DEFAULT NULL ,
  `DESCRIPTION` VARCHAR(254) NULL DEFAULT NULL ,
  PRIMARY KEY (`PERMISSIONID`) )
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jdev`.`ROLE_PERMISSIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdev`.`ROLE_PERMISSIONS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `jdev`.`ROLE_PERMISSIONS` (
  `ROLE_SECURITYROLEID` BIGINT(20) NOT NULL ,
  `ROLE_DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `PERMISSION_PERMISSIONID` INT NOT NULL ,
  PRIMARY KEY (`ROLE_SECURITYROLEID`, `ROLE_DAIRY_DAIRYID`, `PERMISSION_PERMISSIONID`) ,
  INDEX `fk_ROLE_has_PERMISSION_ROLE1` (`ROLE_SECURITYROLEID` ASC, `ROLE_DAIRY_DAIRYID` ASC) ,
  INDEX `fk_ROLE_has_PERMISSION_PERMISSION1` (`PERMISSION_PERMISSIONID` ASC) ,
  CONSTRAINT `fk_ROLE_has_PERMISSION_ROLE1`
    FOREIGN KEY (`ROLE_SECURITYROLEID` , `ROLE_DAIRY_DAIRYID` )
    REFERENCES `jdev`.`ROLE` (`SECURITYROLEID` , `DAIRY_DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROLE_has_PERMISSION_PERMISSION1`
    FOREIGN KEY (`PERMISSION_PERMISSIONID` )
    REFERENCES `jdev`.`PERMISSION` (`PERMISSIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
