SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `dairyreference` ;
CREATE SCHEMA IF NOT EXISTS `dairyreference` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
SHOW WARNINGS;
DROP SCHEMA IF EXISTS `dairymgr` ;
CREATE SCHEMA IF NOT EXISTS `dairymgr` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`CONTAINER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`CONTAINER` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`CONTAINER` (
  `CONTAINER_ID` BIGINT(20) NOT NULL ,
  `CAPACITY` DOUBLE NULL ,
  `UNIT_OF_MEASURE` VARCHAR(15) NULL DEFAULT 'LITRE' ,
  `TAG_TYPE` VARCHAR(15) NULL DEFAULT 'BARCODE' ,
  `TAG_ID` VARCHAR(255) NULL ,
  PRIMARY KEY (`CONTAINER_ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`LOCATION` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`LOCATION` (
  `LOCATIONID` BIGINT(20) NOT NULL ,
  `TAG` VARCHAR(45) NULL ,
  `ADDRESS` VARCHAR(45) NULL ,
  `SECTION` VARCHAR(45) NULL ,
  `ESTATE` VARCHAR(45) NULL ,
  `VILLAGE` VARCHAR(45) NULL ,
  `SUBLOCATION` VARCHAR(45) NULL ,
  `LOCATION` VARCHAR(45) NULL ,
  `DIVISION` VARCHAR(45) NULL ,
  `DISTRICT` VARCHAR(45) NULL ,
  `PROVINCE` VARCHAR(45) NULL ,
  `POSTALCODE` VARCHAR(45) NULL ,
  `LATITUDE` DOUBLE NULL ,
  `LONGITUDE` DOUBLE NULL ,
  `LANDMARKS` VARCHAR(45) NULL ,
  `DIRECTIONS` VARCHAR(45) NULL ,
  `LANDREFERENCENUMBER` VARCHAR(45) NULL ,
  PRIMARY KEY (`LOCATIONID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`PERSON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`PERSON` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`PERSON` (
  `PERSONID` BIGINT(20) NOT NULL ,
  `HONORIFIC` VARCHAR(45) NULL ,
  `FAMILYNAME` VARCHAR(45) NULL ,
  `GIVEN_NAME` VARCHAR(45) NULL ,
  `MIDDLENAME` VARCHAR(45) NULL ,
  `ADDITIONALNAMES` BLOB NULL ,
  `SUFFIX` VARCHAR(45) NULL ,
  `PHOTO` BLOB NULL ,
  PRIMARY KEY (`PERSONID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`ROLE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`ROLE` (
  `SECURITYROLEID` BIGINT(20) NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `SYSTEMDEFINED` TINYINT(1) NULL DEFAULT '0' ,
  `DESCRIPTION` TEXT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`SECURITYROLEID`) ,
  INDEX `fk_SECURITYROLE_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_SECURITYROLE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`EMPLOYEE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`EMPLOYEE` (
  `EMPLOYMENTRELATIONSHIPID` BIGINT(20) NOT NULL ,
  `STARTDATE` DATE NOT NULL ,
  `ENDDATE` DATE NULL ,
  `JOBFUNCTION` VARCHAR(45) NOT NULL ,
  `SYSTEMUSERID` BIGINT(20) NULL ,
  `USERNAME` VARCHAR(45) NULL ,
  `ENCRYPTEDPASSWORD` VARCHAR(45) NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `PERSON_PERSONID` BIGINT(20) NOT NULL ,
  `SECURITYROLE_SECURITYROLEID` BIGINT(20) NOT NULL ,
  `PREVIOUS_EMPLOYMENTID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`EMPLOYMENTRELATIONSHIPID`) ,
  INDEX `fk_EMPLOYEE_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_EMPLOYEE_PERSON1` (`PERSON_PERSONID` ASC) ,
  INDEX `fk_EMPLOYEE_SECURITYROLE1` (`SECURITYROLE_SECURITYROLEID` ASC) ,
  INDEX `fk_EMPLOYEE_EMPLOYEE1` (`PREVIOUS_EMPLOYMENTID` ASC) ,
  CONSTRAINT `fk_EMPLOYEE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_PERSON1`
    FOREIGN KEY (`PERSON_PERSONID` )
    REFERENCES `dairymgr`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_SECURITYROLE1`
    FOREIGN KEY (`SECURITYROLE_SECURITYROLEID` )
    REFERENCES `dairymgr`.`ROLE` (`SECURITYROLEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_EMPLOYEE1`
    FOREIGN KEY (`PREVIOUS_EMPLOYMENTID` )
    REFERENCES `dairymgr`.`EMPLOYEE` (`EMPLOYMENTRELATIONSHIPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`DAIRY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`DAIRY` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`DAIRY` (
  `DAIRYID` BIGINT(20) NOT NULL ,
  `LOCATION_LOCATIONID` BIGINT(20) NOT NULL ,
  `MANAGER` BIGINT(20) NOT NULL ,
  `NAME` VARCHAR(80) NOT NULL ,
  `NHIFNUMBER` VARCHAR(45) NULL ,
  `KDBLICENSENUM` VARCHAR(45) NULL ,
  `NSSFNUMBER` VARCHAR(45) NULL ,
  `PUBLICDESCRIPTION` VARCHAR(45) NULL ,
  `PIN` VARCHAR(45) NULL ,
  `KDBLICENSEEXPIRATIONDATE` DATE NULL ,
  `KDBLICENSEEFFECTIVEDATE` DATE NULL ,
  PRIMARY KEY (`DAIRYID`) ,
  INDEX `fk_DAIRY_LOCATION1` (`LOCATION_LOCATIONID` ASC) ,
  INDEX `fk_DAIRY_EMPLOYEE1` (`MANAGER` ASC) ,
  CONSTRAINT `fk_DAIRY_LOCATION1`
    FOREIGN KEY (`LOCATION_LOCATIONID` )
    REFERENCES `dairymgr`.`LOCATION` (`LOCATIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DAIRY_EMPLOYEE1`
    FOREIGN KEY (`MANAGER` )
    REFERENCES `dairymgr`.`EMPLOYEE` (`EMPLOYMENTRELATIONSHIPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`MEMBERSHIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`MEMBERSHIP` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`MEMBERSHIP` (
  `MEMBERID` INT(11) NOT NULL ,
  `DAIRY` BIGINT(20) NOT NULL ,
  `PERSONID` BIGINT(20) NOT NULL ,
  `APPLICATIONDATE` DATE NOT NULL ,
  `EFFECTIVEDATE` DATE NULL ,
  `STATUS` INT(11) NULL ,
  PRIMARY KEY (`MEMBERID`) ,
  INDEX `fk_MEMBERSHIP_DAIRY1` (`DAIRY` ASC) ,
  INDEX `fk_MEMBERSHIP_PERSON1` (`PERSONID` ASC) ,
  CONSTRAINT `fk_MEMBERSHIP_DAIRY1`
    FOREIGN KEY (`DAIRY` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEMBERSHIP_PERSON1`
    FOREIGN KEY (`PERSONID` )
    REFERENCES `dairymgr`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`ACCOUNT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`ACCOUNT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`ACCOUNT` (
  `ACCOUNTID` BIGINT(20) NOT NULL ,
  `DAIRY` BIGINT(20) NOT NULL ,
  `MEMBER` INT(11) NOT NULL ,
  `TYPE` VARCHAR(45) NOT NULL DEFAULT 'CASH' ,
  `START_DATE` DATE NOT NULL ,
  `END_DATE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ACCOUNTID`) ,
  INDEX `fk_ACCOUNT_MEMBERSHIP1` (`MEMBER` ASC) ,
  INDEX `fk_ACCOUNT_DAIRY1` (`DAIRY` ASC) ,
  CONSTRAINT `fk_ACCOUNT_MEMBERSHIP1`
    FOREIGN KEY (`MEMBER` )
    REFERENCES `dairymgr`.`MEMBERSHIP` (`MEMBERID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACCOUNT_DAIRY1`
    FOREIGN KEY (`DAIRY` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`ACCOUNTTRANSACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`ACCOUNTTRANSACTION` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`ACCOUNTTRANSACTION` (
  `TRANSACTIONID` BIGINT(20) NOT NULL ,
  `ACCOUNTID` BIGINT(20) NOT NULL ,
  `DATE` TIMESTAMP NOT NULL ,
  `TYPE` INT(11) NOT NULL ,
  `SOURCE` VARCHAR(45) NOT NULL ,
  `AMOUNT` DECIMAL(38,0) NOT NULL ,
  `DESCRIPTION` VARCHAR(80) NOT NULL ,
  PRIMARY KEY (`TRANSACTIONID`) ,
  INDEX `fk_ACCOUNTTRANSACTION_ACCOUNT1` (`ACCOUNTID` ASC) ,
  CONSTRAINT `fk_ACCOUNTTRANSACTION_ACCOUNT1`
    FOREIGN KEY (`ACCOUNTID` )
    REFERENCES `dairymgr`.`ACCOUNT` (`ACCOUNTID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`ROUTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`ROUTE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`ROUTE` (
  `ROUTEID` BIGINT(20) NOT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL ,
  PRIMARY KEY (`ROUTEID`) ,
  INDEX `fk_ROUTE_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_ROUTE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`DAIRYLOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`DAIRYLOCATION` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`DAIRYLOCATION` (
  `DAIRYLOCATIONID` BIGINT(20) NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `DAIRY` BIGINT(20) NOT NULL ,
  `LOCATION` BIGINT(20) NOT NULL ,
  `ROUTE` BIGINT(20) NULL ,
  `DATEOPENED` DATE NULL ,
  `PHONENUMBER` VARCHAR(45) NULL ,
  `DESCRIPTION` VARCHAR(45) NULL ,
  `COLORCODE` VARCHAR(45) NULL ,
  PRIMARY KEY (`DAIRYLOCATIONID`) ,
  INDEX `fk_DAIRYLOCATION_DAIRY1` (`DAIRY` ASC) ,
  INDEX `fk_DAIRYLOCATION_ROUTE1` (`ROUTE` ASC) ,
  INDEX `fk_DAIRYLOCATION_LOCATION1` (`LOCATION` ASC) ,
  CONSTRAINT `fk_DAIRYLOCATION_DAIRY1`
    FOREIGN KEY (`DAIRY` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DAIRYLOCATION_ROUTE1`
    FOREIGN KEY (`ROUTE` )
    REFERENCES `dairymgr`.`ROUTE` (`ROUTEID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DAIRYLOCATION_LOCATION1`
    FOREIGN KEY (`LOCATION` )
    REFERENCES `dairymgr`.`LOCATION` (`LOCATIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`FARM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`FARM` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`FARM` (
  `FARMID` BIGINT(20) NOT NULL ,
  `LICENSENUMBER` VARCHAR(45) NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `OWNER` BIGINT(20) NOT NULL ,
  `DEFAULTCOLLECTIONCENTER` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`FARMID`) ,
  INDEX `fk_FARM_PERSON1` (`OWNER` ASC) ,
  INDEX `fk_FARM_DAIRYLOCATION1` (`DEFAULTCOLLECTIONCENTER` ASC) ,
  CONSTRAINT `fk_FARM_PERSON1`
    FOREIGN KEY (`OWNER` )
    REFERENCES `dairymgr`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FARM_DAIRYLOCATION1`
    FOREIGN KEY (`DEFAULTCOLLECTIONCENTER` )
    REFERENCES `dairymgr`.`DAIRYLOCATION` (`DAIRYLOCATIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`REFERENCEANIMALTYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`REFERENCEANIMALTYPE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`REFERENCEANIMALTYPE` (
  `ANIMALTYPEID` INT(11) NOT NULL ,
  `BREED` VARCHAR(45) NOT NULL ,
  `SPECIES` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ANIMALTYPEID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`REGISTEREDANIMAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`REGISTEREDANIMAL` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`REGISTEREDANIMAL` (
  `ANIMNALREGISTRATIONID` BIGINT(20) NOT NULL ,
  `OWNER` BIGINT(20) NOT NULL ,
  `FARM` BIGINT(20) NOT NULL ,
  `PHOTO` BLOB NULL ,
  `GIVENNAME` VARCHAR(45) NOT NULL ,
  `GENDER` INT(11) NOT NULL ,
  `PURPOSE` INT(11) NOT NULL ,
  `REARINGMODE` INT(11) NULL ,
  `BREED` INT(11) NOT NULL ,
  `SIRE_BREED` INT(11) NOT NULL ,
  `IDENTIFYINGFEATURES` TEXT NULL ,
  `DATEOFACQUISITION` DATE NOT NULL ,
  `ACQUISITIONTYPE` INT(11) NULL ,
  `BIRTHDATE` DATE NULL ,
  `PASTOWNERS` TEXT NULL ,
  `INSURANCENUMBER` VARCHAR(45) NULL ,
  PRIMARY KEY (`ANIMNALREGISTRATIONID`) ,
  INDEX `fk_REGISTEREDANIMAL_FARM1` (`FARM` ASC) ,
  INDEX `fk_REGISTEREDANIMAL_REFERENCEANIMALTYPE1` (`BREED` ASC) ,
  INDEX `fk_REGISTEREDANIMAL_PERSON1` (`OWNER` ASC) ,
  INDEX `fk_REGISTEREDANIMAL_REFERENCEANIMALTYPE2` (`SIRE_BREED` ASC) ,
  CONSTRAINT `fk_REGISTEREDANIMAL_FARM1`
    FOREIGN KEY (`FARM` )
    REFERENCES `dairymgr`.`FARM` (`FARMID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REGISTEREDANIMAL_REFERENCEANIMALTYPE1`
    FOREIGN KEY (`BREED` )
    REFERENCES `dairymgr`.`REFERENCEANIMALTYPE` (`ANIMALTYPEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REGISTEREDANIMAL_PERSON1`
    FOREIGN KEY (`OWNER` )
    REFERENCES `dairymgr`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REGISTEREDANIMAL_REFERENCEANIMALTYPE2`
    FOREIGN KEY (`SIRE_BREED` )
    REFERENCES `dairymgr`.`REFERENCEANIMALTYPE` (`ANIMALTYPEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`ANIMALHISTORYRECORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`ANIMALHISTORYRECORD` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`ANIMALHISTORYRECORD` (
  `ANIMALHISTORYRECORDID` BIGINT(20) NOT NULL ,
  `REGISTEREDANIMAL` BIGINT(20) NOT NULL ,
  `NEWSTATUS` INT(11) NOT NULL ,
  `NEWSTATUSDATE` DATE NOT NULL ,
  `STATUSINFO` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ANIMALHISTORYRECORDID`) ,
  INDEX `fk_ANIMALHISTORYRECORD_REGISTEREDANIMAL1` (`REGISTEREDANIMAL` ASC) ,
  CONSTRAINT `fk_ANIMALHISTORYRECORD_REGISTEREDANIMAL1`
    FOREIGN KEY (`REGISTEREDANIMAL` )
    REFERENCES `dairymgr`.`REGISTEREDANIMAL` (`ANIMNALREGISTRATIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`BALANCEPOINT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`BALANCEPOINT` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`BALANCEPOINT` (
  `ACCOUNTBALANCEID` BIGINT(20) NOT NULL ,
  `ACCOUNT_ACCOUNTID` BIGINT(20) NOT NULL ,
  `PREVIOUS_BALANCEPOINT` BIGINT(20) NOT NULL ,
  `AMOUNT` DECIMAL(38,0) NOT NULL ,
  `ASOF` DATETIME NOT NULL ,
  PRIMARY KEY (`ACCOUNTBALANCEID`) ,
  INDEX `fk_BALANCEPOINT_BALANCEPOINT1` (`PREVIOUS_BALANCEPOINT` ASC) ,
  INDEX `fk_BALANCEPOINT_ACCOUNT1` (`ACCOUNT_ACCOUNTID` ASC) ,
  CONSTRAINT `fk_BALANCEPOINT_BALANCEPOINT1`
    FOREIGN KEY (`PREVIOUS_BALANCEPOINT` )
    REFERENCES `dairymgr`.`BALANCEPOINT` (`ACCOUNTBALANCEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BALANCEPOINT_ACCOUNT1`
    FOREIGN KEY (`ACCOUNT_ACCOUNTID` )
    REFERENCES `dairymgr`.`ACCOUNT` (`ACCOUNTID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`ASSET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`ASSET` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`ASSET` (
  `ASSETID` BIGINT(20) NOT NULL ,
  `DATE_ACQUIRED` DATE NULL ,
  `DATE_DISPOSED` DATE NULL ,
  `DISPOSAL_REASON` VARCHAR(45) NULL ,
  `DISPOSAL_METHOD` TEXT NULL ,
  `WITNESS` VARCHAR(45) NULL ,
  `DAMAGES` TEXT NULL ,
  PRIMARY KEY (`ASSETID`) )
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`VEHICLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`VEHICLE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`VEHICLE` (
  `VEHICLEID` BIGINT(20) NOT NULL ,
  `MODEL` VARCHAR(45) NULL ,
  `DOMINANTCOLOUR` VARCHAR(45) NULL ,
  `INSURANCEPOLICYNUMBER` VARCHAR(45) NULL ,
  `CHASSISNUMBER` VARCHAR(45) NULL ,
  `TYPE` VARCHAR(45) NULL ,
  `ENGINENUMBER` VARCHAR(45) NULL ,
  `REGISTRATIONNUMBER` VARCHAR(45) NULL ,
  `LOGBOOKNUMBER` VARCHAR(45) NULL ,
  `INSURANCEPURCHASEDATE` DATE NULL ,
  `CAPACITYINTONNES` DOUBLE NULL ,
  `MODELYEAR` INT(11) NULL ,
  `MAKE` VARCHAR(45) NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `ASSET_ASSETID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`VEHICLEID`) ,
  INDEX `fk_VEHICLE_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_VEHICLE_ASSET1` (`ASSET_ASSETID` ASC) ,
  CONSTRAINT `fk_VEHICLE_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEHICLE_ASSET1`
    FOREIGN KEY (`ASSET_ASSETID` )
    REFERENCES `dairymgr`.`ASSET` (`ASSETID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`COLLECTIONJOURNAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`COLLECTIONJOURNAL` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`COLLECTIONJOURNAL` (
  `ID` BIGINT(20) NOT NULL ,
  `REFERENCENUMBER` VARCHAR(45) NOT NULL ,
  `JOURNALDATE` DATE NOT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `ROUTE` BIGINT(20) NOT NULL ,
  `SESSION` VARCHAR(45) NOT NULL ,
  `DRIVER` BIGINT(20) NULL ,
  `VEHICLE` BIGINT(20) NULL ,
  `JOURNALTOTAL` DECIMAL(38,0) NOT NULL ,
  `FLAGGED` TINYINT(1) NOT NULL DEFAULT '0' ,
  `ENTERED_BY` BIGINT(20) NOT NULL ,
  `ENTRYDATE` TIMESTAMP NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_COLLECTIONJOURNAL_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_COLLECTIONJOURNAL_EMPLOYEE1` (`DRIVER` ASC) ,
  INDEX `fk_COLLECTIONJOURNAL_EMPLOYEE2` (`ENTERED_BY` ASC) ,
  INDEX `fk_COLLECTIONJOURNAL_VEHICLE1` (`VEHICLE` ASC) ,
  INDEX `fk_COLLECTIONJOURNAL_ROUTE1` (`ROUTE` ASC) ,
  CONSTRAINT `fk_COLLECTIONJOURNAL_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COLLECTIONJOURNAL_EMPLOYEE1`
    FOREIGN KEY (`DRIVER` )
    REFERENCES `dairymgr`.`EMPLOYEE` (`EMPLOYMENTRELATIONSHIPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COLLECTIONJOURNAL_EMPLOYEE2`
    FOREIGN KEY (`ENTERED_BY` )
    REFERENCES `dairymgr`.`EMPLOYEE` (`EMPLOYMENTRELATIONSHIPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COLLECTIONJOURNAL_VEHICLE1`
    FOREIGN KEY (`VEHICLE` )
    REFERENCES `dairymgr`.`VEHICLE` (`VEHICLEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COLLECTIONJOURNAL_ROUTE1`
    FOREIGN KEY (`ROUTE` )
    REFERENCES `dairymgr`.`ROUTE` (`ROUTEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`FARM_CONTAINER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`FARM_CONTAINER` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`FARM_CONTAINER` (
  `CANID` BIGINT(20) NOT NULL ,
  `CONTAINER_CONTAINERID` BIGINT(20) NOT NULL ,
  `FARM_FARMID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`CANID`) ,
  INDEX `fk_CAN_CONTAINER1` (`CONTAINER_CONTAINERID` ASC) ,
  INDEX `fk_FARMERCONTAINER_FARM1` (`FARM_FARMID` ASC) ,
  CONSTRAINT `fk_CAN_CONTAINER1`
    FOREIGN KEY (`CONTAINER_CONTAINERID` )
    REFERENCES `dairymgr`.`CONTAINER` (`CONTAINER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FARMERCONTAINER_FARM1`
    FOREIGN KEY (`FARM_FARMID` )
    REFERENCES `dairymgr`.`FARM` (`FARMID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`DAIRY_CONTAINER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`DAIRY_CONTAINER` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`DAIRY_CONTAINER` (
  `CANID` BIGINT(20) NOT NULL ,
  `CONTAINER_CONTAINERID` BIGINT(20) NOT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `ROUTE_ROUTEID` BIGINT(20) NOT NULL ,
  `ASSET_ASSETID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`CANID`) ,
  INDEX `fk_BIN_CONTAINER1` (`CONTAINER_CONTAINERID` ASC) ,
  INDEX `fk_DAIRYCONTAINER_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_DAIRYCONTAINER_ROUTE1` (`ROUTE_ROUTEID` ASC) ,
  INDEX `fk_DAIRYCONTAINER_ASSET1` (`ASSET_ASSETID` ASC) ,
  CONSTRAINT `fk_BIN_CONTAINER1`
    FOREIGN KEY (`CONTAINER_CONTAINERID` )
    REFERENCES `dairymgr`.`CONTAINER` (`CONTAINER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DAIRYCONTAINER_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DAIRYCONTAINER_ROUTE1`
    FOREIGN KEY (`ROUTE_ROUTEID` )
    REFERENCES `dairymgr`.`ROUTE` (`ROUTEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DAIRYCONTAINER_ASSET1`
    FOREIGN KEY (`ASSET_ASSETID` )
    REFERENCES `dairymgr`.`ASSET` (`ASSETID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`COLLECTIONRECORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`COLLECTIONRECORD` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`COLLECTIONRECORD` (
  `COLLECTIONRECORDID` BIGINT(20) NOT NULL ,
  `COLLECTIONJOURNAL_ID` BIGINT(20) NOT NULL ,
  `JOURNALSEQUENCE` INT(11) NOT NULL ,
  `RECORDEDMEMBERID` VARCHAR(45) NOT NULL ,
  `VALID_MEMBERID` INT(11) NULL ,
  `MILKQUANTITY` DECIMAL(38,0) NOT NULL ,
  `UNIT_OF_MEASURE` VARCHAR(15) NULL DEFAULT 'LITER' ,
  `COLLECTED_FROM_CAN` BIGINT(20) NULL ,
  `MIXED_INTO_BIN` BIGINT(20) NOT NULL ,
  `OFFROUTE` TINYINT(1) NOT NULL DEFAULT '0' ,
  `REJECTED` TINYINT(1) NOT NULL DEFAULT '0' ,
  `NOTRECORDED` TINYINT(1) NOT NULL DEFAULT '0' ,
  `FLAGGED` TINYINT(1) NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`COLLECTIONRECORDID`) ,
  INDEX `fk_COLLECTIONRECORD_MEMBERSHIP1` (`VALID_MEMBERID` ASC) ,
  INDEX `fk_COLLECTIONRECORD_FARM_CONTAINER1` (`COLLECTED_FROM_CAN` ASC) ,
  INDEX `fk_COLLECTIONRECORD_DAIRY_CONTAINER1` (`MIXED_INTO_BIN` ASC) ,
  INDEX `fk_COLLECTIONRECORD_COLLECTIONJOURNAL1` (`COLLECTIONJOURNAL_ID` ASC) ,
  CONSTRAINT `fk_COLLECTIONRECORD_MEMBERSHIP1`
    FOREIGN KEY (`VALID_MEMBERID` )
    REFERENCES `dairymgr`.`MEMBERSHIP` (`MEMBERID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COLLECTIONRECORD_FARM_CONTAINER1`
    FOREIGN KEY (`COLLECTED_FROM_CAN` )
    REFERENCES `dairymgr`.`FARM_CONTAINER` (`CANID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COLLECTIONRECORD_DAIRY_CONTAINER1`
    FOREIGN KEY (`MIXED_INTO_BIN` )
    REFERENCES `dairymgr`.`DAIRY_CONTAINER` (`CANID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COLLECTIONRECORD_COLLECTIONJOURNAL1`
    FOREIGN KEY (`COLLECTIONJOURNAL_ID` )
    REFERENCES `dairymgr`.`COLLECTIONJOURNAL` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`CONTACTMETHOD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`CONTACTMETHOD` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`CONTACTMETHOD` (
  `CONTACTMETHODID` BIGINT(20) NOT NULL ,
  `CONTACTINFO` VARCHAR(45) NULL ,
  `CONTACTTYPE` INT(11) NULL ,
  `PERSON_PERSONID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`CONTACTMETHODID`) ,
  INDEX `fk_CONTACTMETHOD_PERSON1` (`PERSON_PERSONID` ASC) ,
  CONSTRAINT `fk_CONTACTMETHOD_PERSON1`
    FOREIGN KEY (`PERSON_PERSONID` )
    REFERENCES `dairymgr`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`LOGINHISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`LOGINHISTORY` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`LOGINHISTORY` (
  `LOGINHISTORYID` BIGINT(20) NOT NULL ,
  `TIMESTAMP` DATETIME NOT NULL ,
  `IPADDRESS` VARCHAR(45) NOT NULL ,
  `EMPLOYEE_EMPLOYMENTRELATIONSHIPID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`LOGINHISTORYID`) ,
  INDEX `fk_LOGINHISTORY_EMPLOYEE1` (`EMPLOYEE_EMPLOYMENTRELATIONSHIPID` ASC) ,
  CONSTRAINT `fk_LOGINHISTORY_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_EMPLOYMENTRELATIONSHIPID` )
    REFERENCES `dairymgr`.`EMPLOYEE` (`EMPLOYMENTRELATIONSHIPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`MILKPRICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`MILKPRICE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`MILKPRICE` (
  `PRICEID` BIGINT(20) NOT NULL ,
  `DAIRY` BIGINT(20) NOT NULL ,
  `PRICEDATE` DATE NOT NULL ,
  `PRICE` DECIMAL(38,0) NOT NULL ,
  PRIMARY KEY (`PRICEID`) ,
  INDEX `fk_MILKPRICE_DAIRY1` (`DAIRY` ASC) ,
  UNIQUE INDEX `PRICEDATE_UNIQUE` (`PRICEDATE` ASC) ,
  CONSTRAINT `fk_MILKPRICE_DAIRY1`
    FOREIGN KEY (`DAIRY` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`SEQUENCE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`SEQUENCE` (
  `SEQ_NAME` VARCHAR(50) NOT NULL ,
  `SEQ_COUNT` DECIMAL(38,0) NULL DEFAULT NULL ,
  PRIMARY KEY (`SEQ_NAME`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`SUPPLIER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`SUPPLIER` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`SUPPLIER` (
  `SUPPLIERID` BIGINT(20) NOT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `STATUS` INT(11) NOT NULL ,
  `CATEGORY_LIST` VARCHAR(45) NULL ,
  `DESCRIPTION` VARCHAR(45) NOT NULL ,
  `REGISTRATIONDATE` DATE NULL ,
  `EXPIRATIONDATE` BIGINT(20) NULL ,
  `CONTACT` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`SUPPLIERID`) ,
  INDEX `fk_SUPPLIER_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  INDEX `fk_SUPPLIER_PERSON1` (`CONTACT` ASC) ,
  CONSTRAINT `fk_SUPPLIER_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUPPLIER_PERSON1`
    FOREIGN KEY (`CONTACT` )
    REFERENCES `dairymgr`.`PERSON` (`PERSONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`PERMISSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`PERMISSION` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`PERMISSION` (
  `PERMISSIONID` BIGINT(20) NOT NULL ,
  `SHORTNAME` VARCHAR(45) NULL ,
  `DESCRIPTION` VARCHAR(254) NULL ,
  PRIMARY KEY (`PERMISSIONID`) )
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`ROLE_PERMISSIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`ROLE_PERMISSIONS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`ROLE_PERMISSIONS` (
  `ROLE_SECURITYROLEID` BIGINT(20) NOT NULL ,
  `PERMISSION_PERMISSIONID` BIGINT(20) NOT NULL ,
  INDEX `fk_ROLE_PERMISSIONS_ROLE1` (`ROLE_SECURITYROLEID` ASC) ,
  INDEX `fk_ROLE_PERMISSIONS_PERMISSION1` (`PERMISSION_PERMISSIONID` ASC) ,
  CONSTRAINT `fk_ROLE_PERMISSIONS_ROLE1`
    FOREIGN KEY (`ROLE_SECURITYROLEID` )
    REFERENCES `dairymgr`.`ROLE` (`SECURITYROLEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROLE_PERMISSIONS_PERMISSION1`
    FOREIGN KEY (`PERMISSION_PERMISSIONID` )
    REFERENCES `dairymgr`.`PERMISSION` (`PERMISSIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`DAIRY_SERVICETYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`DAIRY_SERVICETYPES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`DAIRY_SERVICETYPES` (
  `SERVICETYPEID` INT(11)  NOT NULL ,
  `DAIRY_DAIRYID` BIGINT(20) NOT NULL ,
  `SHORTNAME` VARCHAR(15) NOT NULL ,
  `DISPLAYNAME` VARCHAR(45) NOT NULL ,
  `DESCRIPTION` TEXT NULL ,
  PRIMARY KEY (`SERVICETYPEID`) ,
  INDEX `fk_REFERENCE_SERVICETYPES_DAIRY1` (`DAIRY_DAIRYID` ASC) ,
  CONSTRAINT `fk_REFERENCE_SERVICETYPES_DAIRY1`
    FOREIGN KEY (`DAIRY_DAIRYID` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`DAIRYLOCATION_SERVICES_OFFERED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`DAIRYLOCATION_SERVICES_OFFERED` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`DAIRYLOCATION_SERVICES_OFFERED` (
  `DAIRYLOCATION_DAIRYLOCATIONID` BIGINT(20) NOT NULL ,
  `DAIRY_SERVICETYPES_SERVICETYPEID` INT(11)  NOT NULL ,
  PRIMARY KEY (`DAIRYLOCATION_DAIRYLOCATIONID`, `DAIRY_SERVICETYPES_SERVICETYPEID`) ,
  INDEX `fk_DAIRYLOCATION_has_DAIRY_SERVICETYPES_DAIRYLOCATION1` (`DAIRYLOCATION_DAIRYLOCATIONID` ASC) ,
  INDEX `fk_DAIRYLOCATION_has_DAIRY_SERVICETYPES_DAIRY_SERVICETYPES1` (`DAIRY_SERVICETYPES_SERVICETYPEID` ASC) ,
  CONSTRAINT `fk_DAIRYLOCATION_has_DAIRY_SERVICETYPES_DAIRYLOCATION1`
    FOREIGN KEY (`DAIRYLOCATION_DAIRYLOCATIONID` )
    REFERENCES `dairymgr`.`DAIRYLOCATION` (`DAIRYLOCATIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DAIRYLOCATION_has_DAIRY_SERVICETYPES_DAIRY_SERVICETYPES1`
    FOREIGN KEY (`DAIRY_SERVICETYPES_SERVICETYPEID` )
    REFERENCES `dairymgr`.`DAIRY_SERVICETYPES` (`SERVICETYPEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dairymgr`.`HEALTH_REQUEST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dairymgr`.`HEALTH_REQUEST` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `dairymgr`.`HEALTH_REQUEST` (
  `REQUESTID` INT NOT NULL ,
  `MEMBER` INT(11) NOT NULL ,
  `DAIRY` BIGINT(20) NOT NULL ,
  `FARM` BIGINT(20) NOT NULL ,
  `REQUEST_DATE` VARCHAR(45) NOT NULL ,
  `REQUEST_TYPE` VARCHAR(15) NOT NULL ,
  `REGISTEREDANIMAL_ANIMNALREGISTRATIONID` BIGINT(20) NULL ,
  `HEAT_OBSERVED` DATE NULL ,
  `FIRST_APPLICATION` DATE NULL ,
  `SECOND_APPLICATION` DATE NULL ,
  `THIRD_APPLICATION` DATE NULL ,
  `REQUEST_DESCRIPTION` TEXT NULL ,
  `ASSIGNED_TO` BIGINT(20) NULL ,
  PRIMARY KEY (`REQUESTID`) ,
  INDEX `fk_HEALTH_REQUEST_DAIRY1` (`DAIRY` ASC) ,
  INDEX `fk_HEALTH_REQUEST_FARM1` (`FARM` ASC) ,
  INDEX `fk_HEALTH_REQUEST_MEMBERSHIP1` (`MEMBER` ASC) ,
  INDEX `fk_HEALTH_REQUEST_REGISTEREDANIMAL1` (`REGISTEREDANIMAL_ANIMNALREGISTRATIONID` ASC) ,
  INDEX `fk_HEALTH_REQUEST_SUPPLIER1` (`ASSIGNED_TO` ASC) ,
  CONSTRAINT `fk_HEALTH_REQUEST_DAIRY1`
    FOREIGN KEY (`DAIRY` )
    REFERENCES `dairymgr`.`DAIRY` (`DAIRYID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HEALTH_REQUEST_FARM1`
    FOREIGN KEY (`FARM` )
    REFERENCES `dairymgr`.`FARM` (`FARMID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HEALTH_REQUEST_MEMBERSHIP1`
    FOREIGN KEY (`MEMBER` )
    REFERENCES `dairymgr`.`MEMBERSHIP` (`MEMBERID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HEALTH_REQUEST_REGISTEREDANIMAL1`
    FOREIGN KEY (`REGISTEREDANIMAL_ANIMNALREGISTRATIONID` )
    REFERENCES `dairymgr`.`REGISTEREDANIMAL` (`ANIMNALREGISTRATIONID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HEALTH_REQUEST_SUPPLIER1`
    FOREIGN KEY (`ASSIGNED_TO` )
    REFERENCES `dairymgr`.`SUPPLIER` (`SUPPLIERID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
